<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("offer");
?>

<?
if(!empty($_GET['offer-filter'])){
	$GLOBALS['filterOffer'] = array("PROPERTY_folder_id" => $_GET['offer-filter']);
}
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"offer", 
	array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "vin",
			1 => "service_auto_apply",
			2 => "poi_id",
			3 => "currency",
			4 => "video",
			5 => "exchange",
			6 => "time",
			7 => "year",
			8 => "registry_year",
			9 => "contact",
			10 => "action",
			11 => "OPTION_EQU",
			12 => "sale_services",
			13 => "ICON_GAS",
			14 => "ICON_PAZZL",
			15 => "ICON_REMEN",
			16 => "ICON_SPEED",
			17 => "name",
			18 => "SLIDER_IMAGE_ONE",
			19 => "interior_code",
			20 => "modification_code",
			21 => "color_code",
			22 => "equipment_code",
			23 => "owners_number",
			24 => "CUZOV",
			25 => "mark_id",
			26 => "folder_id",
			27 => "modification_id",
			28 => "warranty_expire",
			29 => "CAPACITY",
			30 => "description",
			31 => "extras",
			32 => "armored",
			33 => "availability",
			34 => "metallic",
			35 => "run",
			36 => "wheel",
			37 => "contact_info",
			38 => "sts",
			39 => "CREDIT",
			40 => "SLIDER",
			41 => "SLOGAN",
			42 => "state",
			43 => "SpecId",
			44 => "DEFAULT_COMPLIT",
			45 => "OLD_PRICE",
			46 => "custom",
			47 => "TEXT_GAS",
			48 => "TEXT_PAZZL",
			49 => "TEXT_REMEN",
			50 => "TEXT_SPEED",
			51 => "number",
			52 => "phone",
			53 => "body_type",
			54 => "pts",
			55 => "TRANSMISS",
			56 => "STREET",
			57 => "unique_id",
			58 => "images",
			59 => "color",
			60 => "discount_price",
			61 => "NEW_PRICE",
			62 => "IMAGES_FON_1",
			63 => "IMAGES_FON_2",
			64 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "8",
		"IBLOCK_TYPE" => "products",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "CREDIT",
			1 => "SLIDER",
			2 => "OLD_PRICE",
			3 => "NEW_PRICE",
			4 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "160",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/offer/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "offer",
		"FILTER_NAME" => "filterOffer",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "folder_id",
			1 => "",
		),
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>

<div class="clear"></div>

	<br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>