<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
$APPLICATION->SetTitle("");
?><?

switch($_REQUEST['order']){
	case "DESC":
		$order = "DESC";
		$sort = "PROPERTY_".$_REQUEST['sort'];
		break;

	case "ASC":
		$order = "ASC";
		$sort = "PROPERTY_".$_REQUEST['sort'];
		break;

	default:
		$order = "ASC";
		$sort = "PROPERTY_NEW_PRICE";
}

?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"auto-mileage",
	Array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array("",""),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array("STREET","GARANTY","ENGINE","COUNT_USER","MODEL","POWER","GRAR_TYPE","MILEAGE","CAPACITY","STANDART","PHONE","FUEL_TYPE","TRANSMISS","COLOR","NEW_PRICE","YEAR","META_DESCRIPTION","META_KEYWORDS","META_TITLE","SAT_SEO_TEXT","VIN","DOP","SPEED_TIME","SELECTION_PRICE","EMISSION","PROFIT","SEATS","GEAR","EQUIPMENT","MAX_WEIGHT","MAX_SPEED","MAXIMUM_TORQUE","FULL_WEIGHT","NAME_SHORT","NAME_DROM","PACK_NAME","AVITO_MIN_DESC","DESCRIDTION_AVITO_XML","CHAR","REMAINING","OPTIONS","PACKS","ADD_FOR_AVITO_OFFER","CONSUMPTION","DISCOUNT","PACK_ITEMS","SERVICE","LINK1","LINK2","PRICE_COMPLECTATION","PRICE_DOP","PRICE_OPTIONS","TRANSMISS_TOORBO","FON_IMAGES_SLIDER","COLOR_DROM","PACK_PRICE","PRICE_ALL","OLD_PRICE",""),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILE_404" => "",
		"FILTER_FIELD_CODE" => array("",""),
		"FILTER_NAME" => "",
		"FILTER_PROPERTY_CODE" => array("MODEL","MILEAGE","TRANSMISS","NEW_PRICE","YEAR",""),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "37",
		"IBLOCK_TYPE" => "products",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array("",""),
		"LIST_PROPERTY_CODE" => array("STREET","GARANTY","ENGINE","COUNT_USER","MODEL","POWER","GRAR_TYPE","MILEAGE","CAPACITY","STANDART","PHONE","FUEL_TYPE","TRANSMISS","COLOR","NEW_PRICE","YEAR","META_DESCRIPTION","META_KEYWORDS","META_TITLE","SAT_SEO_TEXT","VIN","DOP","SPEED_TIME","SELECTION_PRICE","EMISSION","PROFIT","SEATS","GEAR","EQUIPMENT","MAX_WEIGHT","MAX_SPEED","MAXIMUM_TORQUE","FULL_WEIGHT","NAME_SHORT","NAME_DROM","PACK_NAME","AVITO_MIN_DESC","DESCRIDTION_AVITO_XML","CHAR","REMAINING","OPTIONS","PACKS","ADD_FOR_AVITO_OFFER","CONSUMPTION","DISCOUNT","PACK_ITEMS","SERVICE","LINK1","LINK2","PRICE_COMPLECTATION","PRICE_DOP","PRICE_OPTIONS","TRANSMISS_TOORBO","FON_IMAGES_SLIDER","COLOR_DROM","PACK_PRICE","PRICE_ALL","OLD_PRICE",""),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "100",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/hpromise/avtomobili-s-probegom/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => Array("detail"=>"#ELEMENT_CODE#/","news"=>"","section"=>""),
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => $sort,
		"SORT_BY2" => $sort,
		"SORT_ORDER1" => $order,
		"SORT_ORDER2" => $order,
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N"
	)
);?>